<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;

    protected $table = 'invoices';
    
    protected $fillable = [
        'invoice_number',
        'company_id',
        'subscription_id',
        'project_name',
        'invoice_date',
        'due_date',
        'amount',
        'sub_total',
        'tax_amount',
        'discount_amount',
        'currency',
        'exchange_rate',
        'status',
        'paid_amount',
        'paid_date',
        'invoice_month',
        'billing_address',
        'shipping_address',
        'items',
        'payment_gateway',
        'offline_payment_method',
        'transaction_id',
        'bank_account',
        'payment_details',
        'notes',
        'terms',
        'generated_by',
        'created_at',
        'updated_at'
    ];

    protected $casts = [
        'invoice_date' => 'date',
        'due_date' => 'date',
        'invoice_month' => 'date',
        'paid_date' => 'datetime',
        'amount' => 'decimal:2',
        'sub_total' => 'decimal:2',
        'tax_amount' => 'decimal:2',
        'discount_amount' => 'decimal:2',
        'paid_amount' => 'decimal:2',
        'exchange_rate' => 'decimal:4',
        'items' => 'array', // JSON column ko array mein cast karo
    ];

    // ========== RELATIONSHIPS ==========
    
    // Company relation
    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }

    // Generated by relation (User)
    public function generator()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    // 🔥 PAYMENTS RELATIONSHIP (YEH ADD KARO)
    public function payments()
    {
        return $this->hasMany(Payment::class, 'invoice_id', 'id');
    }

    // Subscription package relation (if exists)
    public function subscription()
    {
        return $this->belongsTo(SubscriptionPackage::class, 'subscription_id');
    }

    // ========== HELPER METHODS ==========

    // Get status badge class
    public function getStatusBadge()
    {
        $badges = [
            'pending' => 'badge bg-warning',
            'paid' => 'badge bg-success',
            'overdue' => 'badge bg-danger',
            'cancelled' => 'badge bg-secondary',
            'draft' => 'badge bg-info'
        ];
        
        return $badges[$this->status] ?? 'badge bg-secondary';
    }

    // Get status text
    public function getStatusText()
    {
        return ucfirst($this->status);
    }

    // Helper methods
    public function isPaid()
    {
        return $this->status === 'paid';
    }

    public function isOverdue()
    {
        return $this->status === 'overdue' || 
               ($this->status === 'pending' && $this->due_date < now());
    }

    public function getRemainingAmount()
    {
        return $this->amount - ($this->paid_amount ?? 0);
    }
    
    // Get total paid from payments table
    public function getTotalPaidFromPayments()
    {
        return $this->payments()
            ->where('payment_status', 'completed')
            ->sum('total_amount');
    }
    
    // Get payment count
    public function getPaymentCount()
    {
        return $this->payments()
            ->where('payment_status', 'completed')
            ->count();
    }
    
    // Check if fully paid from payments
    public function isFullyPaidFromPayments()
    {
        return $this->getTotalPaidFromPayments() >= $this->amount;
    }
    
    // Calculate totals from items
    public function calculateTotals()
    {
        $items = $this->items ?? [];
        $subTotal = 0;
        $taxAmount = 0;
        
        foreach ($items as $item) {
            $itemTotal = ($item['quantity'] ?? 1) * ($item['unit_price'] ?? 0);
            $subTotal += $itemTotal;
            
            if (isset($item['tax']) && $item['tax'] > 0) {
                $taxAmount += $itemTotal * ($item['tax'] / 100);
            }
        }
        
        $this->sub_total = $subTotal;
        $this->tax_amount = $taxAmount;
        $this->amount = $subTotal + $taxAmount - ($this->discount_amount ?? 0);
        
        return $this;
    }
}